spring:
  config:
    import: application-secret.yaml  # secret 파일 불러오기

  application:
    name: GP

  datasource:
    url: jdbc:h2:mem:gpdb;
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: false
    datasource:
      driver-class-name: org.h2.Driver



  jpa:
    hibernate:
      ddl-auto: create-drop
      # 나중에 배포시 create-drop대신 update로 바꿔야함.
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
    defer-datasource-initialization: true

  sql:
    init:
      mode: always
      schema-locations: classpath:db/schema.sql
      encoding: UTF-8

  # Spring Mail 설정 추가 (Gmail 기준)
  mail:
    host: smtp.gmail.com
    port: 587
    username:   # 공백처리 -> application-secret.yaml에 생성 시 본인 Gmail 주소 덮어씀
    password: # 공백처리 -> application-secret.yaml에 생성 시 본인 Gmail 주소 덮어씀
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

#    Gmail 앱 비밀번호 발급 방법
#    1단계 - 2단계 인증 활성화
#
#    myaccount.google.com 접속
#    왼쪽 메뉴 보안 클릭
#    2단계 인증 → 활성화
#
#    2단계 - 앱 비밀번호 발급
#
#    Google 계정 검색창에 "앱 비밀번호" 검색
#    앱 이름 아무거나 입력 (예: GP) → 만들기
#    생성된 16자리 비밀번호 복사 (공백 제거하고 사용)

jwt:
  issuer: GP
  
  # TODO scretKey: ${JWT_SCRET_KEY}
  secretKey: "asdfqwrt!@#QWEASDE#@ESAXc1241234"

  access:
    # 액세스 토큰 만료시간 1시간 : 1000(ms -> s) * 60 (s -> m) * 60(m -> h)
    expiration: 3600000
    header: Authorization

  refresh:
    # 리프레시 토큰 만료시간 1주
    expiration: 604800000
    header: Refresh-Token
server:
  port: 8080

