spring:
  application:
    name: GP

  datasource:
    url: jdbc:h2:mem:gpdb;
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: false
    datasource:
      driver-class-name: org.h2.Driver



  jpa:
    hibernate:
      ddl-auto: create-drop
      # 나중에 배포시 create-drop대신 update로 바꿔야함.
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
    defer-datasource-initialization: true

  sql:
    init:
      mode: always
      schema-locations: classpath:db/schema.sql

server:
  port: 8080
